### ISSUE TITLE
Randomly truncated output

### ISSUE THREAD

**Issue by zwily** [d11wtq/dockerpty#26]
Given this script:

```python
#!/usr/bin/env python

from docker.client import Client
from docker.utils import kwargs_from_env
import dockerpty

client = Client(**kwargs_from_env())
container = client.create_container(image="debian:wheezy", stdin_open=True, tty=True, command='seq 200')
dockerpty.start(client, container)
```

When I run it, about half the time I see the full output (1..200, each on their own line), and the other half the time it just prints "1" (with no newline) and exits:

```bash
zach $ ./test.py 
1zach $ 
```

I'm using boot2docker on OS X, if that makes a difference. I tried against https://github.com/d11wtq/dockerpty/pull/25 as well, thinking it may be related, but still get the truncated output. Originally noticed using fig: https://github.com/docker/fig/issues/658.

**Comment by Leland-Takamine** [comment]
Any update on this? Also seeing this problem.

**Comment by foresmac** [comment]
This definitely happens running Django management commands (tests, shell, etc) via `fig run`. So I've basically switched to just running it via docker directly, i.e. `docker exec -it project_web_1 python manage.py test`. This works perfectly, so it seems odd that it would only affect boot2docker users when using fig (which then relies on dockerpty).

**Comment by michaelstandley** [comment]
I think https://github.com/d11wtq/dockerpty/pull/35 fixes this, can it be merged?

**Comment by aanand** [comment]
#35 still hasn't fixed it for me. Pinging @d11wtq and @dnephin, who have some experience with the code.

I'm pretty sure it's the `break` command here that's causing it to exit:

```python
def _hijack_tty(self, pumps):
    with tty.Terminal(sys.stdin, raw=self.israw()):
        self.resize()
        while True:
            ready = io.select(pumps, timeout=60)
            try:
                if any([p.flush() is None for p in ready]):
                    break
            except SSLError as e:
                if 'The operation did not complete' not in e.strerror:
                    raise e
```

As I understand it, we've got a list of `io.Pump` objects here - each one is reading from a socket and writing to another (e.g. reading from a TCP socket representing the container's `stdout` and writing to `sys.stdout`).

Inside the `select` loop, we're flushing each of the pumps that's ready to go. The pump's `flush` method says that it returns `None` "if EOF has been reached" - reading the code for `flush`, that seems to mean that either `write()` on the pump's writer stream has returned `None`, or `EPIPE` has been raised by either the reader or the writer stream.

If I stick some debug in and run a container with `seq 2000` as in the example, I can see that, whenever the program exits prematurely:

- `ready` has two pumps in it: stdout and stderr
- the stdout pump hasn't returned `None` from `p.flush()` (i.e. it's still going)
- the stderr pump *has* returned `None` from `p.flush()` (i.e. it's reached EOF)
- because `write()` on the stderr stream (an `io.Stream` object) has returned `None`
- because `io.Stream.write()` has been passed `''` to write, a case it [explicitly detects and shortcuts](https://github.com/d11wtq/dockerpty/blob/e336a8f7f28a2f1f4048603be28929c9787864bb/dockerpty/io.py#L129-L130), returning `None`

I'm still trying to piece together what's supposed to be happening:

- Is it OK that we're trying to write `''` to `stderr`? Even if it isn't, it doesn't seem like that should bring everything to a halt.
- Is it OK that `io.Stream.write()` shortcuts and returns `None` if you pass it an empty chunk?
- Is it OK that `_hijack_tty` exits as soon as one pump is done? We [changed it once](https://github.com/d11wtq/dockerpty/commit/6ded9260d9c7f9d4761fbc2d70281b994d159126) to wait for all of them to be done, but this resulted in hanging, so we [reverted it](https://github.com/d11wtq/dockerpty/pull/23). It'd be good to reason this out once and for all.

**Comment by zwily** [comment]
I think the problem is right here:

https://github.com/d11wtq/dockerpty/blob/master/dockerpty/io.py#L137

`os.write` doesn't guarantee that it will write all bytes, but the code clearly assumes it does. You can't just loop there either and write - you need to wait for the destination stream to have room, so it needs to join in the main select loop. I'm taking a stab at it.

**Comment by zwily** [comment]
Here's my attempt to fix this: https://github.com/zwily/dockerpty/commit/f0660e55c7acdc1953b3f04ad706859e611dfed4

It's not super clean, but I can't get any more truncation with it, no matter what I do. Does someone want to try it out before I submit a PR?
